apiVersion: v1
kind: Secret
metadata:
  name: traffic-guru-db-cred
type: Opaque
stringData:
  DATABASE_HOST: {{.Values.database.host}}
  DATABASE_PORT: {{.Values.database.port|quote}}
  DATABASE_USERNAME: {{.Values.database.username}}
  DATABASE_PASSWORD: {{.Values.database.password}}
  DATABASE_NAME: {{.Values.database.db}}
  DATABASE_TYPE: {{.Values.database.type}}

